installationId: public-a
mode: postgresql
replicaCount: 3

image:
  repository: ghcr.io/memeloop-online/memeloop-workspace-control
  tag: latest
  digest: sha256:25f62b76f22ae4acab17ce0bd4c87de8afcc24962ed366181a3e7d972e679651

database:
  postgresSecretName: mwc-public-a-database

secrets:
  encryptionSecretName: mwc-public-a-encryption
  internalAuthSecretName: mwc-public-a-internal-auth

workspace:
  storageClassName: managed-delete
  ttydImage: tsl0922/ttyd:1.7.7

public:
  sshHost: ssh.example.com
  apiDomain: workspaces.example.com
  webShellDomain: shell.example.com
  webShellOrigin: https://shell.example.com

higress:
  extAuthPluginUrl: oci://higress-registry.cn-hangzhou.cr.aliyuncs.com/plugins/ext-auth@sha256:7179a769128a6db8612242ae4ccc1486d0cf48eacacbf56445c85915d7c9c2bf

jumpHost:
  image:
    repository: ghcr.io/memeloop-online/memeloop-workspace-control-ssh-jump
    tag: latest
    digest: sha256:e4d9c26644aef7764769e4c0ae5ff8b446aa2021d483f50d465118d2b7da4824
  hostKeySecretName: mwc-public-a-jump-host-key

autoscaling:
  customMetrics:
    enabled: true
