import { makeStyles, tokens } from "@fluentui/react-components";

/** Shared Fluent 2 layout tokens for the workspace surface. */
export const useWorkspaceStyles = makeStyles({
  page: {
    display: "grid",
    gap: tokens.spacingVerticalXXL,
    padding: `${tokens.spacingVerticalXL} ${tokens.spacingHorizontalXXL} ${tokens.spacingVerticalXXXL}`,
    maxWidth: "1440px",
    margin: "0 auto",
    width: "100%",
    boxSizing: "border-box",
    "@media (max-width: 760px)": {
      padding: `${tokens.spacingVerticalL} ${tokens.spacingHorizontalM} ${tokens.spacingVerticalXXL}`,
      gap: tokens.spacingVerticalXL,
    },
  },
  header: {
    display: "flex",
    alignItems: "flex-end",
    justifyContent: "space-between",
    gap: tokens.spacingHorizontalL,
    flexWrap: "wrap",
  },
  headerText: { display: "grid", gap: tokens.spacingVerticalXS, minWidth: 0 },
  eyebrow: { color: tokens.colorBrandForeground1, fontWeight: tokens.fontWeightSemibold, letterSpacing: "0.08em", textTransform: "uppercase" },
  heading: { margin: 0 },
  headerActions: { display: "flex", gap: tokens.spacingHorizontalS, flexWrap: "wrap" },
  filters: {
    display: "grid",
    gridTemplateColumns: "minmax(220px, 1fr) auto",
    alignItems: "end",
    gap: tokens.spacingHorizontalL,
    "@media (max-width: 760px)": { gridTemplateColumns: "1fr" },
  },
  searchField: { minWidth: 0 },
  pagination: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: tokens.spacingHorizontalS,
    flexWrap: "wrap",
  },
  paginationStatus: { color: tokens.colorNeutralForeground2, textAlign: "center", flex: "1 1 auto" },
  list: { display: "grid", gap: tokens.spacingVerticalM, minWidth: 0 },
  card: {
    display: "grid",
    gap: tokens.spacingVerticalL,
    minWidth: 0,
    padding: tokens.spacingHorizontalL,
    borderRadius: tokens.borderRadiusLarge,
    border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`,
    backgroundColor: tokens.colorNeutralBackground1,
    boxShadow: tokens.shadow4,
    transitionProperty: "box-shadow, border-color",
    transitionDuration: tokens.durationNormal,
    "@media (max-width: 760px)": { padding: tokens.spacingHorizontalM },
  },
  cardHeader: { display: "flex", alignItems: "flex-start", justifyContent: "space-between", gap: tokens.spacingHorizontalM, minWidth: 0 },
  cardTitle: { display: "grid", gap: tokens.spacingVerticalXXS, minWidth: 0 },
  titleText: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  idText: { color: tokens.colorNeutralForeground3, fontFamily: tokens.fontFamilyMonospace, fontSize: tokens.fontSizeBase200 },
  metadata: { display: "flex", alignItems: "center", flexWrap: "wrap", gap: `${tokens.spacingVerticalXS} ${tokens.spacingHorizontalM}`, color: tokens.colorNeutralForeground2, minWidth: 0 },
  metadataCode: { fontFamily: tokens.fontFamilyMonospace, fontSize: tokens.fontSizeBase200, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  toolbar: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: tokens.spacingHorizontalM, flexWrap: "wrap", minWidth: 0 },
  toolbarGroup: { display: "flex", alignItems: "center", gap: tokens.spacingHorizontalXS, flexWrap: "wrap" },
  toolbarGroupEnd: { display: "flex", alignItems: "center", gap: tokens.spacingHorizontalXS, flexWrap: "wrap", marginInlineStart: "auto" },
  dangerButton: { color: tokens.colorPaletteRedForeground1 },
  resourceGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 160px), 1fr))", gap: tokens.spacingHorizontalS },
  meter: { display: "grid", gap: tokens.spacingVerticalXS, minWidth: 0, padding: tokens.spacingHorizontalM, borderRadius: tokens.borderRadiusMedium, backgroundColor: tokens.colorNeutralBackground2 },
  meterHeader: { display: "flex", justifyContent: "space-between", alignItems: "baseline", gap: tokens.spacingHorizontalXS },
  meterValue: { fontFamily: tokens.fontFamilyMonospace, fontWeight: tokens.fontWeightSemibold, whiteSpace: "nowrap" },
  meterTrack: { height: "6px", overflow: "hidden", borderRadius: tokens.borderRadiusCircular, backgroundColor: tokens.colorNeutralStroke2 },
  meterFill: { height: "100%", borderRadius: tokens.borderRadiusCircular, backgroundColor: tokens.colorBrandBackground, transitionProperty: "width", transitionDuration: tokens.durationNormal },
  meterHint: { color: tokens.colorNeutralForeground3 },
  statusPanel: { display: "grid", gap: tokens.spacingVerticalM, padding: tokens.spacingHorizontalM, borderRadius: tokens.borderRadiusMedium, backgroundColor: tokens.colorNeutralBackground2 },
  panelHeading: { display: "flex", alignItems: "center", justifyContent: "space-between", gap: tokens.spacingHorizontalM, margin: 0 },
  podGrid: { display: "grid", gap: tokens.spacingVerticalXS },
  podRow: { display: "grid", gridTemplateColumns: "minmax(0, 2fr) auto auto auto", alignItems: "center", gap: tokens.spacingHorizontalM, padding: tokens.spacingVerticalS, borderRadius: tokens.borderRadiusMedium, backgroundColor: tokens.colorNeutralBackground1, "@media (max-width: 640px)": { gridTemplateColumns: "minmax(0, 1fr) auto" } },
  code: { fontFamily: tokens.fontFamilyMonospace, fontSize: tokens.fontSizeBase200, overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  eventList: { display: "grid", gap: tokens.spacingVerticalS, maxHeight: "360px", overflowY: "auto" },
  event: { display: "grid", gap: tokens.spacingVerticalXXS, padding: tokens.spacingVerticalS, borderLeft: `${tokens.strokeWidthThick} solid ${tokens.colorBrandBackground}`, backgroundColor: tokens.colorNeutralBackground1 },
  eventMeta: { color: tokens.colorNeutralForeground3 },
  statsGrid: { display: "grid", gridTemplateColumns: "repeat(auto-fit, minmax(min(100%, 180px), 1fr))", gap: tokens.spacingHorizontalM, "@media (max-width: 480px)": { gridTemplateColumns: "1fr 1fr", gap: tokens.spacingHorizontalS } },
  stat: { position: "relative", display: "grid", gap: tokens.spacingVerticalXS, minHeight: "100px", overflow: "hidden", padding: tokens.spacingHorizontalL, borderRadius: tokens.borderRadiusLarge, border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`, backgroundColor: tokens.colorNeutralBackground1, "@media (max-width: 480px)": { padding: tokens.spacingHorizontalM, minHeight: "88px" } },
  statFill: { position: "absolute", insetInlineStart: 0, insetBlockEnd: 0, height: "4px", backgroundColor: tokens.colorBrandBackground, transitionProperty: "width", transitionDuration: tokens.durationNormal },
  statLabel: { color: tokens.colorNeutralForeground2 },
  statValue: { fontFamily: tokens.fontFamilyMonospace, fontSize: tokens.fontSizeBase500, fontWeight: tokens.fontWeightSemibold, letterSpacing: "-0.03em", overflow: "hidden", textOverflow: "ellipsis" },
  statHint: { color: tokens.colorNeutralForeground3, minHeight: "1.2em" },
  createCard: { display: "grid", gap: tokens.spacingVerticalL, padding: tokens.spacingHorizontalL, borderRadius: tokens.borderRadiusLarge, border: `${tokens.strokeWidthThin} solid ${tokens.colorBrandStroke1}`, backgroundColor: tokens.colorNeutralBackground2 },
  formGrid: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: tokens.spacingVerticalL, "@media (max-width: 680px)": { gridTemplateColumns: "1fr" } },
  formWide: { gridColumn: "1 / -1" },
  templateSummary: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: tokens.spacingVerticalS, margin: 0, padding: tokens.spacingHorizontalM, borderRadius: tokens.borderRadiusMedium, backgroundColor: tokens.colorNeutralBackground1, "@media (max-width: 680px)": { gridTemplateColumns: "1fr" } },
  summaryItem: { display: "grid", gap: tokens.spacingVerticalXXS, minWidth: 0 },
  summaryLabel: { color: tokens.colorNeutralForeground3 },
  summaryValue: { overflow: "hidden", textOverflow: "ellipsis", whiteSpace: "nowrap" },
  formActions: { display: "flex", justifyContent: "flex-end", gap: tokens.spacingHorizontalS, flexWrap: "wrap" },
  dialogSurface: { maxWidth: "720px", width: "min(720px, calc(100vw - 32px))" },
  dialogBody: { display: "grid", gap: tokens.spacingVerticalL },
  dialogSection: { display: "grid", gap: tokens.spacingVerticalS },
  dialogFacts: { display: "grid", gridTemplateColumns: "repeat(2, minmax(0, 1fr))", gap: tokens.spacingVerticalS, margin: 0, "@media (max-width: 560px)": { gridTemplateColumns: "1fr" } },
  dialogFact: { display: "grid", gap: tokens.spacingVerticalXXS, minWidth: 0 },
  copyBlock: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", alignItems: "start", gap: tokens.spacingHorizontalS, padding: tokens.spacingHorizontalM, borderRadius: tokens.borderRadiusMedium, border: `${tokens.strokeWidthThin} solid ${tokens.colorNeutralStroke2}`, backgroundColor: tokens.colorNeutralBackground2, minWidth: 0 },
  copyValue: { margin: 0, minWidth: 0, overflow: "auto", whiteSpace: "pre-wrap", wordBreak: "break-word", fontFamily: tokens.fontFamilyMonospace, fontSize: tokens.fontSizeBase200 },
  dialogActions: { display: "flex", justifyContent: "flex-end", gap: tokens.spacingHorizontalS, flexWrap: "wrap" },
  portList: { display: "grid", gap: tokens.spacingVerticalS, maxHeight: "360px", overflowY: "auto" },
  portRow: { display: "grid", gridTemplateColumns: "minmax(0, 1fr) auto", gap: tokens.spacingHorizontalM, alignItems: "center", padding: tokens.spacingHorizontalM, borderRadius: tokens.borderRadiusMedium, backgroundColor: tokens.colorNeutralBackground2, "@media (max-width: 600px)": { gridTemplateColumns: "1fr" } },
  portMain: { display: "grid", gap: tokens.spacingVerticalXXS, minWidth: 0 },
  portActions: { display: "flex", gap: tokens.spacingHorizontalXS, flexWrap: "wrap", justifyContent: "flex-end" },
  notice: { display: "flex", alignItems: "center", gap: tokens.spacingHorizontalS },
  empty: { display: "grid", placeItems: "center", minHeight: "140px", padding: tokens.spacingHorizontalL, color: tokens.colorNeutralForeground2, borderRadius: tokens.borderRadiusMedium, backgroundColor: tokens.colorNeutralBackground2 },
});
